server:
  port: 8082
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
feign:
  httpclient:
    enabled: true
    max-connections: 100
    max-connections-per-route: 10
    connection-timeout: 3000
dubbo:
  application:
    name: user-service1
  registry:
    address: nacos://localhost:8848
    check: false
  protocol:
    port: 21881
    name: dubbo
  consumer:
    check: false

seata:
  enabled: true
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: localhost:8848
      group: DEFAULT_GROUP
      cluster: default
  tx-service-group: test
  service:
    vgroup-mapping:
      test: default
  data-source-proxy-mode: AT
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
      web-context-unify: false
rocketmq:
  name-server: 192.168.204.128:7981
  producer:
    group: default_group
    retry-times-when-send-async-failed: 2
    retry-next-server: true
