#nacos:
#  config:
#    auto-refresh: true
#    server-addr: localhost:8848
#    bootstrap:
#      enable: true
#    data-id: test
server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8091/eureka