server:
  port: 8081
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
dubbo:
  application:
    name: book-service
  registry:
    address: nacos://localhost:8848
  protocol:
    port: 21880
    name: dubbo
seata:
  enabled: true
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: localhost:8848
      group: DEFAULT_GROUP
      cluster: default
  tx-service-group: test
  service:
    vgroup-mapping:
      test: default
  data-source-proxy-mode: AT